// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package compilation_job

import (
	"context"

	ackv1alpha1 "github.com/aws/aws-controllers-k8s/apis/core/v1alpha1"
	ackcompare "github.com/aws/aws-controllers-k8s/pkg/compare"
	ackerr "github.com/aws/aws-controllers-k8s/pkg/errors"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/sagemaker"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws/aws-controllers-k8s/services/sagemaker/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = &svcsdk.SageMaker{}
	_ = &svcapitypes.CompilationJob{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.DescribeCompilationJobWithContext(ctx, input)
	if respErr != nil {
		if awsErr, ok := ackerr.AWSError(respErr); ok && awsErr.Code() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.CompilationJobArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.CompilationJobArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required by not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.CompilationJobName == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeCompilationJobInput, error) {
	res := &svcsdk.DescribeCompilationJobInput{}

	if r.ko.Spec.CompilationJobName != nil {
		res.SetCompilationJobName(*r.ko.Spec.CompilationJobName)
	}

	return res, nil
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.ListCompilationJobsInput, error) {
	res := &svcsdk.ListCompilationJobsInput{}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a new resource with any fields in the Status field filled in
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newCreateRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.CreateCompilationJobWithContext(ctx, input)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.CompilationJobArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.CompilationJobArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	ko.Status.Conditions = []*ackv1alpha1.Condition{}
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	r *resource,
) (*svcsdk.CreateCompilationJobInput, error) {
	res := &svcsdk.CreateCompilationJobInput{}

	if r.ko.Spec.CompilationJobName != nil {
		res.SetCompilationJobName(*r.ko.Spec.CompilationJobName)
	}
	if r.ko.Spec.InputConfig != nil {
		f1 := &svcsdk.InputConfig{}
		if r.ko.Spec.InputConfig.DataInputConfig != nil {
			f1.SetDataInputConfig(*r.ko.Spec.InputConfig.DataInputConfig)
		}
		if r.ko.Spec.InputConfig.Framework != nil {
			f1.SetFramework(*r.ko.Spec.InputConfig.Framework)
		}
		if r.ko.Spec.InputConfig.S3URI != nil {
			f1.SetS3Uri(*r.ko.Spec.InputConfig.S3URI)
		}
		res.SetInputConfig(f1)
	}
	if r.ko.Spec.OutputConfig != nil {
		f2 := &svcsdk.OutputConfig{}
		if r.ko.Spec.OutputConfig.CompilerOptions != nil {
			f2.SetCompilerOptions(*r.ko.Spec.OutputConfig.CompilerOptions)
		}
		if r.ko.Spec.OutputConfig.S3OutputLocation != nil {
			f2.SetS3OutputLocation(*r.ko.Spec.OutputConfig.S3OutputLocation)
		}
		if r.ko.Spec.OutputConfig.TargetDevice != nil {
			f2.SetTargetDevice(*r.ko.Spec.OutputConfig.TargetDevice)
		}
		if r.ko.Spec.OutputConfig.TargetPlatform != nil {
			f2f3 := &svcsdk.TargetPlatform{}
			if r.ko.Spec.OutputConfig.TargetPlatform.Accelerator != nil {
				f2f3.SetAccelerator(*r.ko.Spec.OutputConfig.TargetPlatform.Accelerator)
			}
			if r.ko.Spec.OutputConfig.TargetPlatform.Arch != nil {
				f2f3.SetArch(*r.ko.Spec.OutputConfig.TargetPlatform.Arch)
			}
			if r.ko.Spec.OutputConfig.TargetPlatform.Os != nil {
				f2f3.SetOs(*r.ko.Spec.OutputConfig.TargetPlatform.Os)
			}
			f2.SetTargetPlatform(f2f3)
		}
		res.SetOutputConfig(f2)
	}
	if r.ko.Spec.RoleARN != nil {
		res.SetRoleArn(*r.ko.Spec.RoleARN)
	}
	if r.ko.Spec.StoppingCondition != nil {
		f4 := &svcsdk.StoppingCondition{}
		if r.ko.Spec.StoppingCondition.MaxRuntimeInSeconds != nil {
			f4.SetMaxRuntimeInSeconds(*r.ko.Spec.StoppingCondition.MaxRuntimeInSeconds)
		}
		if r.ko.Spec.StoppingCondition.MaxWaitTimeInSeconds != nil {
			f4.SetMaxWaitTimeInSeconds(*r.ko.Spec.StoppingCondition.MaxWaitTimeInSeconds)
		}
		res.SetStoppingCondition(f4)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	diffReporter *ackcompare.Reporter,
) (*resource, error) {
	// TODO(jaypipes): Figure this out...
	return nil, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) error {
	// TODO(jaypipes): Figure this out...
	return nil

}
