apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: adopt-s3-bucket
spec:
  kubernetes:
    group: s3.services.k8s.aws
    kind: Bucket
  aws:
    nameOrID: "nithomso-test-bucket"