// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws/aws-controllers-k8s/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ModelPackageSpec defines the desired state of ModelPackage
type ModelPackageSpec struct {
	CertifyForMarketplace        *bool                                `json:"certifyForMarketplace,omitempty"`
	InferenceSpecification       *InferenceSpecification              `json:"inferenceSpecification,omitempty"`
	ModelPackageDescription      *string                              `json:"modelPackageDescription,omitempty"`
	ModelPackageName             *string                              `json:"modelPackageName,omitempty"`
	SourceAlgorithmSpecification *SourceAlgorithmSpecification        `json:"sourceAlgorithmSpecification,omitempty"`
	ValidationSpecification      *ModelPackageValidationSpecification `json:"validationSpecification,omitempty"`
}

// ModelPackageStatus defines the observed state of ModelPackage
type ModelPackageStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// ModelPackage is the Schema for the ModelPackages API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ModelPackage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ModelPackageSpec   `json:"spec,omitempty"`
	Status            ModelPackageStatus `json:"status,omitempty"`
}

// ModelPackageList contains a list of ModelPackage
// +kubebuilder:object:root=true
type ModelPackageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ModelPackage `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ModelPackage{}, &ModelPackageList{})
}
