// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws/aws-controllers-k8s/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PresignedNotebookInstanceURLSpec defines the desired state of PresignedNotebookInstanceURL
type PresignedNotebookInstanceURLSpec struct {
	NotebookInstanceName               *string `json:"notebookInstanceName,omitempty"`
	SessionExpirationDurationInSeconds *int64  `json:"sessionExpirationDurationInSeconds,omitempty"`
}

// PresignedNotebookInstanceURLStatus defines the observed state of PresignedNotebookInstanceURL
type PresignedNotebookInstanceURLStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions    []*ackv1alpha1.Condition `json:"conditions"`
	AuthorizedURL *string                  `json:"authorizedURL,omitempty"`
}

// PresignedNotebookInstanceURL is the Schema for the PresignedNotebookInstanceURLS API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type PresignedNotebookInstanceURL struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PresignedNotebookInstanceURLSpec   `json:"spec,omitempty"`
	Status            PresignedNotebookInstanceURLStatus `json:"status,omitempty"`
}

// PresignedNotebookInstanceURLList contains a list of PresignedNotebookInstanceURL
// +kubebuilder:object:root=true
type PresignedNotebookInstanceURLList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PresignedNotebookInstanceURL `json:"items"`
}

func init() {
	SchemeBuilder.Register(&PresignedNotebookInstanceURL{}, &PresignedNotebookInstanceURLList{})
}
