// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws/aws-controllers-k8s/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TrialComponentSpec defines the desired state of TrialComponent
type TrialComponentSpec struct {
	DisplayName        *string                                  `json:"displayName,omitempty"`
	EndTime            *metav1.Time                             `json:"endTime,omitempty"`
	InputArtifacts     map[string]*TrialComponentArtifact       `json:"inputArtifacts,omitempty"`
	OutputArtifacts    map[string]*TrialComponentArtifact       `json:"outputArtifacts,omitempty"`
	Parameters         map[string]*TrialComponentParameterValue `json:"parameters,omitempty"`
	StartTime          *metav1.Time                             `json:"startTime,omitempty"`
	Status             *TrialComponentStatus_SDK                `json:"status,omitempty"`
	Tags               []*Tag                                   `json:"tags,omitempty"`
	TrialComponentName *string                                  `json:"trialComponentName,omitempty"`
}

// TrialComponentStatus defines the observed state of TrialComponent
type TrialComponentStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// TrialComponent is the Schema for the TrialComponents API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type TrialComponent struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TrialComponentSpec   `json:"spec,omitempty"`
	Status            TrialComponentStatus `json:"status,omitempty"`
}

// TrialComponentList contains a list of TrialComponent
// +kubebuilder:object:root=true
type TrialComponentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrialComponent `json:"items"`
}

func init() {
	SchemeBuilder.Register(&TrialComponent{}, &TrialComponentList{})
}
