// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package workforce

import (
	"context"

	ackv1alpha1 "github.com/aws/aws-controllers-k8s/apis/core/v1alpha1"
	ackcompare "github.com/aws/aws-controllers-k8s/pkg/compare"
	ackerr "github.com/aws/aws-controllers-k8s/pkg/errors"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/sagemaker"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws/aws-controllers-k8s/services/sagemaker/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = &svcsdk.SageMaker{}
	_ = &svcapitypes.Workforce{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.DescribeWorkforceWithContext(ctx, input)
	if respErr != nil {
		if awsErr, ok := ackerr.AWSError(respErr); ok && awsErr.Code() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Workforce.WorkforceArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Workforce.WorkforceArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required by not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.WorkforceName == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeWorkforceInput, error) {
	res := &svcsdk.DescribeWorkforceInput{}

	if r.ko.Spec.WorkforceName != nil {
		res.SetWorkforceName(*r.ko.Spec.WorkforceName)
	}

	return res, nil
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.ListWorkforcesInput, error) {
	res := &svcsdk.ListWorkforcesInput{}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a new resource with any fields in the Status field filled in
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newCreateRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.CreateWorkforceWithContext(ctx, input)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.WorkforceArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.WorkforceArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	ko.Status.Conditions = []*ackv1alpha1.Condition{}
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	r *resource,
) (*svcsdk.CreateWorkforceInput, error) {
	res := &svcsdk.CreateWorkforceInput{}

	if r.ko.Spec.CognitoConfig != nil {
		f0 := &svcsdk.CognitoConfig{}
		if r.ko.Spec.CognitoConfig.ClientID != nil {
			f0.SetClientId(*r.ko.Spec.CognitoConfig.ClientID)
		}
		if r.ko.Spec.CognitoConfig.UserPool != nil {
			f0.SetUserPool(*r.ko.Spec.CognitoConfig.UserPool)
		}
		res.SetCognitoConfig(f0)
	}
	if r.ko.Spec.OidcConfig != nil {
		f1 := &svcsdk.OidcConfig{}
		if r.ko.Spec.OidcConfig.AuthorizationEndpoint != nil {
			f1.SetAuthorizationEndpoint(*r.ko.Spec.OidcConfig.AuthorizationEndpoint)
		}
		if r.ko.Spec.OidcConfig.ClientID != nil {
			f1.SetClientId(*r.ko.Spec.OidcConfig.ClientID)
		}
		if r.ko.Spec.OidcConfig.ClientSecret != nil {
			f1.SetClientSecret(*r.ko.Spec.OidcConfig.ClientSecret)
		}
		if r.ko.Spec.OidcConfig.Issuer != nil {
			f1.SetIssuer(*r.ko.Spec.OidcConfig.Issuer)
		}
		if r.ko.Spec.OidcConfig.JwksURI != nil {
			f1.SetJwksUri(*r.ko.Spec.OidcConfig.JwksURI)
		}
		if r.ko.Spec.OidcConfig.LogoutEndpoint != nil {
			f1.SetLogoutEndpoint(*r.ko.Spec.OidcConfig.LogoutEndpoint)
		}
		if r.ko.Spec.OidcConfig.TokenEndpoint != nil {
			f1.SetTokenEndpoint(*r.ko.Spec.OidcConfig.TokenEndpoint)
		}
		if r.ko.Spec.OidcConfig.UserInfoEndpoint != nil {
			f1.SetUserInfoEndpoint(*r.ko.Spec.OidcConfig.UserInfoEndpoint)
		}
		res.SetOidcConfig(f1)
	}
	if r.ko.Spec.SourceIPConfig != nil {
		f2 := &svcsdk.SourceIpConfig{}
		if r.ko.Spec.SourceIPConfig.CIDRs != nil {
			f2f0 := []*string{}
			for _, f2f0iter := range r.ko.Spec.SourceIPConfig.CIDRs {
				var f2f0elem string
				f2f0elem = *f2f0iter
				f2f0 = append(f2f0, &f2f0elem)
			}
			f2.SetCidrs(f2f0)
		}
		res.SetSourceIpConfig(f2)
	}
	if r.ko.Spec.Tags != nil {
		f3 := []*svcsdk.Tag{}
		for _, f3iter := range r.ko.Spec.Tags {
			f3elem := &svcsdk.Tag{}
			if f3iter.Key != nil {
				f3elem.SetKey(*f3iter.Key)
			}
			if f3iter.Value != nil {
				f3elem.SetValue(*f3iter.Value)
			}
			f3 = append(f3, f3elem)
		}
		res.SetTags(f3)
	}
	if r.ko.Spec.WorkforceName != nil {
		res.SetWorkforceName(*r.ko.Spec.WorkforceName)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	diffReporter *ackcompare.Reporter,
) (*resource, error) {

	input, err := rm.newUpdateRequestPayload(desired)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.UpdateWorkforceWithContext(ctx, input)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Workforce.WorkforceArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Workforce.WorkforceArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	r *resource,
) (*svcsdk.UpdateWorkforceInput, error) {
	res := &svcsdk.UpdateWorkforceInput{}

	if r.ko.Spec.OidcConfig != nil {
		f0 := &svcsdk.OidcConfig{}
		if r.ko.Spec.OidcConfig.AuthorizationEndpoint != nil {
			f0.SetAuthorizationEndpoint(*r.ko.Spec.OidcConfig.AuthorizationEndpoint)
		}
		if r.ko.Spec.OidcConfig.ClientID != nil {
			f0.SetClientId(*r.ko.Spec.OidcConfig.ClientID)
		}
		if r.ko.Spec.OidcConfig.ClientSecret != nil {
			f0.SetClientSecret(*r.ko.Spec.OidcConfig.ClientSecret)
		}
		if r.ko.Spec.OidcConfig.Issuer != nil {
			f0.SetIssuer(*r.ko.Spec.OidcConfig.Issuer)
		}
		if r.ko.Spec.OidcConfig.JwksURI != nil {
			f0.SetJwksUri(*r.ko.Spec.OidcConfig.JwksURI)
		}
		if r.ko.Spec.OidcConfig.LogoutEndpoint != nil {
			f0.SetLogoutEndpoint(*r.ko.Spec.OidcConfig.LogoutEndpoint)
		}
		if r.ko.Spec.OidcConfig.TokenEndpoint != nil {
			f0.SetTokenEndpoint(*r.ko.Spec.OidcConfig.TokenEndpoint)
		}
		if r.ko.Spec.OidcConfig.UserInfoEndpoint != nil {
			f0.SetUserInfoEndpoint(*r.ko.Spec.OidcConfig.UserInfoEndpoint)
		}
		res.SetOidcConfig(f0)
	}
	if r.ko.Spec.SourceIPConfig != nil {
		f1 := &svcsdk.SourceIpConfig{}
		if r.ko.Spec.SourceIPConfig.CIDRs != nil {
			f1f0 := []*string{}
			for _, f1f0iter := range r.ko.Spec.SourceIPConfig.CIDRs {
				var f1f0elem string
				f1f0elem = *f1f0iter
				f1f0 = append(f1f0, &f1f0elem)
			}
			f1.SetCidrs(f1f0)
		}
		res.SetSourceIpConfig(f1)
	}
	if r.ko.Spec.WorkforceName != nil {
		res.SetWorkforceName(*r.ko.Spec.WorkforceName)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) error {
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return err
	}
	_, respErr := rm.sdkapi.DeleteWorkforceWithContext(ctx, input)
	return respErr
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteWorkforceInput, error) {
	res := &svcsdk.DeleteWorkforceInput{}

	if r.ko.Spec.WorkforceName != nil {
		res.SetWorkforceName(*r.ko.Spec.WorkforceName)
	}

	return res, nil
}
